# Generated by Django 5.1.3 on 2024-12-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanresult",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
